### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by S7RL7SAbsPfLB8tS** [slow/account-ruiner#1]
if the user doesnt own the server, instead of just leaving it could check if the user has admin / ban perms and utilize these perms to destroy the server by deleting all channels/ banning all members and so on depending on what perms the user has. after finishing the nuke it can then leave

**Comment by slow** [comment]
I was thinking of connecting a server nuker with this, problem with that is I don't have a reliable way of scraping the member list with a user account. However I believe as long as the user has Administrator permissions it shouldn't be hard to scrape them. I'll most likely be releasing the server nuker separately and integrate it into the account ruiner soon enough.
