### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by ItzBoiz** [slow/account-ruiner#3]
Can you separately make a Discord Server nuker in which we put the victim human's token and the server ID, so that that person creates spammed channels in loop and raids everything. My suggested features:

- custom channel name (the channels which will be in loop)
- message spammer in created channels (custom)
- rols nuker
- all channels deleter
- people banner

please if you want to make a nuker, you can add features which you like

**Comment by slow** [comment]
this is outside of the scope of an account ruiner
